name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for the issue! 👍 We've got it and we're on it. Your input helps us improve. Stay tuned for updates!"
        pr-message: "Thanks for the PR! 👏 Your code rocks! Let's review and merge. Keep coding awesome!"
