name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: "Thanks for the issue! 👍 We've got it and we're on it. Your input helps us improve. Stay tuned for updates!"
      pull-requests: "Thanks for the PR! 👏 Your code rocks! Let's review and merge. Keep coding awesome!"
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
